import { Inter } from "next/font/google";
import "../globals.css";
import AuthProvider from "@/components/AuthProvider";
import Navbar from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <AuthProvider>
      <html lang="en">
      <body className={inter.className}>
          
        <div className='flex flex-col'>
          <Navbar/>

         <div>
          {children}
         </div> 

        </div>
       
      </body>
    </html>
    </AuthProvider>
    
  );
}
